apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-pipeline.configMapName" . }}
  namespace: {{ include "telemetry-pipeline.namespace" . }}
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
data:
  pipeline.k8s.yaml: |
{{ .Files.Get (printf "files/%s" .Values.config.pipelineFile) | indent 4 }}
  sensors.yaml: |
{{ .Files.Get (printf "files/%s" .Values.config.sensorsFile) | indent 4 }}