{{- if and .Values.pipeline.enabled .Values.pipeline.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}
  namespace: {{ include "telemetry-pipeline.namespace" . }}
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "telemetry-pipeline.fullname" . }}
  minReplicas: {{ .Values.pipeline.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.pipeline.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pipeline.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}