{{- if .Values.pipeline.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-pipeline.pipelineServiceName" . }}
  namespace: {{ include "telemetry-pipeline.namespace" . }}
  labels:
    {{- include "telemetry-pipeline.pipelineLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: telemetry-pipeline
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}