{{- if .Values.simulator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-simulator
  namespace: {{ include "telemetry-pipeline.namespace" . }}
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
    app: telemetry-simulator
spec:
  replicas: {{ .Values.simulator.replicas }}
  selector:
    matchLabels:
      app: telemetry-simulator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: telemetry-simulator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.podSecurity.enabled }}
      securityContext:
        {{- include "telemetry-pipeline.pythonPodSecurityContext" . | nindent 8 }}
      {{- end }}
      containers:
        - name: simulator
          image: "{{ .Values.images.simulator.repository }}:{{ .Values.images.simulator.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- if .Values.podSecurity.enabled }}
          securityContext:
            {{- include "telemetry-pipeline.pythonContainerSecurityContext" . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          command:
            - sh
            - -c
            - |
              sleep {{ .Values.simulator.startupSleepSeconds }}
              telemetry-simulator --config /app/config/pipeline.k8s.yaml --sensors /app/config/sensors.yaml --duration {{ .Values.simulator.durationSeconds }}
          resources:
            {{- toYaml .Values.simulator.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "telemetry-pipeline.configMapName" . }}
{{- end }}