{{- if .Values.victoriametrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telemetry-pipeline.fullname" . }}-vm-scrape
  namespace: {{ include "telemetry-pipeline.namespace" . }}
  labels:
    {{- include "telemetry-pipeline.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.victoriametrics.scrapeInterval }}
      evaluation_interval: {{ .Values.victoriametrics.scrapeInterval }}
    scrape_configs:
      - job_name: telemetry-pipeline
        static_configs:
          - targets: ["{{ include "telemetry-pipeline.pipelineServiceName" . }}:{{ .Values.service.port }}"]
        metrics_path: /metrics
{{- end }}