apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: telemetry
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: redpandadata/redpanda:v24.1.5
          command:
            - /bin/sh
            - -c
            - |
              rpk topic create telemetry.events -p 3 -r 1 --brokers redpanda:9092 || true
              echo "topic ready"